/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day7;

/**
 *
 * @author Krish
 */
public class KalkulatorsArPogam extends javax.swing.JFrame {

    double skaitlis1;
    double skaitlis2;
    String darbiba;
    /**
     * Creates new form KalkulatorsArPogam
     */
    public KalkulatorsArPogam() {
        initComponents();
        
        this.cipars0.setText("0");
        this.cipars1.setText("1");
        this.cipars2.setText("2");
        this.cipars3.setText("3");
        this.cipars4.setText("4");
        this.cipars5.setText("5");
        this.cipars6.setText("6");
        this.cipars7.setText("7");
        this.cipars8.setText("8");
        this.cipars9.setText("9");
        this.atnemt.setText("-");
        this.dalit.setText("/");
        this.reizinat.setText("*");
        this.saskaitit.setText("+");
        this.vienads.setText("=");
        this.notirit.setText("C");
        this.dispejs.setText("");
        this.dispejs.setEnabled(false);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dispejs = new javax.swing.JTextField();
        cipars7 = new javax.swing.JButton();
        cipars4 = new javax.swing.JButton();
        cipars8 = new javax.swing.JButton();
        cipars9 = new javax.swing.JButton();
        dalit = new javax.swing.JButton();
        cipars5 = new javax.swing.JButton();
        reizinat = new javax.swing.JButton();
        cipars6 = new javax.swing.JButton();
        cipars1 = new javax.swing.JButton();
        cipars2 = new javax.swing.JButton();
        cipars3 = new javax.swing.JButton();
        cipars0 = new javax.swing.JButton();
        atnemt = new javax.swing.JButton();
        notirit = new javax.swing.JButton();
        saskaitit = new javax.swing.JButton();
        vienads = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dispejs.setText("jTextField1");

        cipars7.setText("jButton1");
        cipars7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipars7ActionPerformed(evt);
            }
        });

        cipars4.setText("jButton1");
        cipars4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipars4ActionPerformed(evt);
            }
        });

        cipars8.setText("jButton1");
        cipars8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipars8ActionPerformed(evt);
            }
        });

        cipars9.setText("jButton1");
        cipars9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipars9ActionPerformed(evt);
            }
        });

        dalit.setText("jButton1");
        dalit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dalitActionPerformed(evt);
            }
        });

        cipars5.setText("jButton1");
        cipars5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipars5ActionPerformed(evt);
            }
        });

        reizinat.setText("jButton1");
        reizinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reizinatActionPerformed(evt);
            }
        });

        cipars6.setText("jButton1");
        cipars6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipars6ActionPerformed(evt);
            }
        });

        cipars1.setText("jButton1");
        cipars1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipars1ActionPerformed(evt);
            }
        });

        cipars2.setText("jButton1");
        cipars2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipars2ActionPerformed(evt);
            }
        });

        cipars3.setText("jButton1");
        cipars3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipars3ActionPerformed(evt);
            }
        });

        cipars0.setText("jButton1");
        cipars0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipars0ActionPerformed(evt);
            }
        });

        atnemt.setText("jButton1");
        atnemt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atnemtActionPerformed(evt);
            }
        });

        notirit.setText("jButton1");
        notirit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notiritActionPerformed(evt);
            }
        });

        saskaitit.setText("jButton1");
        saskaitit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saskaititActionPerformed(evt);
            }
        });

        vienads.setText("jButton1");
        vienads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vienadsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(dispejs, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cipars7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cipars8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cipars9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dalit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cipars4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cipars5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cipars6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reizinat, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cipars0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(cipars1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cipars2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notirit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cipars3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(atnemt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(vienads, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saskaitit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dispejs, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cipars7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cipars8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cipars9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dalit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cipars4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cipars5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cipars6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reizinat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cipars1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cipars2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cipars3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atnemt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cipars0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saskaitit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vienads, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notirit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cipars7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipars7ActionPerformed
       int septini = 7;
        this.dispejs.setText(dispejs.getText() + String.valueOf(septini));
    }//GEN-LAST:event_cipars7ActionPerformed

    private void cipars8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipars8ActionPerformed
        int astoni = 8;
        this.dispejs.setText(dispejs.getText() + String.valueOf(astoni));
    }//GEN-LAST:event_cipars8ActionPerformed

    private void cipars9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipars9ActionPerformed
        int devini = 9;
        this.dispejs.setText(dispejs.getText() + String.valueOf(devini));
    }//GEN-LAST:event_cipars9ActionPerformed

    private void cipars4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipars4ActionPerformed
        int cetri = 4;
        this.dispejs.setText(dispejs.getText() + String.valueOf(cetri));
    }//GEN-LAST:event_cipars4ActionPerformed

    private void cipars5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipars5ActionPerformed
        int pieci = 5;
        this.dispejs.setText(dispejs.getText() + String.valueOf(pieci));
    }//GEN-LAST:event_cipars5ActionPerformed

    private void cipars6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipars6ActionPerformed
        int sesi = 6;
        this.dispejs.setText(dispejs.getText() + String.valueOf(sesi));
    }//GEN-LAST:event_cipars6ActionPerformed

    private void cipars1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipars1ActionPerformed
        int viens = 1;
        this.dispejs.setText(dispejs.getText() + String.valueOf(viens));
    }//GEN-LAST:event_cipars1ActionPerformed

    private void cipars2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipars2ActionPerformed
        int divi = 2;
        this.dispejs.setText(dispejs.getText() + String.valueOf(divi));
    }//GEN-LAST:event_cipars2ActionPerformed

    private void cipars3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipars3ActionPerformed
        int tris = 3;
        this.dispejs.setText(dispejs.getText() + String.valueOf(tris));
    }//GEN-LAST:event_cipars3ActionPerformed

    private void cipars0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipars0ActionPerformed
        int nulle = 0;
        this.dispejs.setText(dispejs.getText() + String.valueOf(nulle));
    }//GEN-LAST:event_cipars0ActionPerformed

    private void dalitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dalitActionPerformed
        String teksts = this.dispejs.getText();
        skaitlis1 = Double.valueOf(teksts);
        darbiba = "/";
        this.dispejs.setText("");
        
    }//GEN-LAST:event_dalitActionPerformed

    private void reizinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reizinatActionPerformed
        String teksts = this.dispejs.getText();
        skaitlis1 = Double.valueOf(teksts);
        darbiba = "*";
        this.dispejs.setText("");
    }//GEN-LAST:event_reizinatActionPerformed

    private void atnemtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atnemtActionPerformed
        String teksts = this.dispejs.getText();
        skaitlis1 = Double.valueOf(teksts);
        darbiba = "-";
        this.dispejs.setText("");
    }//GEN-LAST:event_atnemtActionPerformed

    private void saskaititActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saskaititActionPerformed
        String teksts = this.dispejs.getText();
        skaitlis1 = Double.valueOf(teksts);
        darbiba = "+";
        this.dispejs.setText("");
    }//GEN-LAST:event_saskaititActionPerformed

    private void vienadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vienadsActionPerformed
        String teksts = this.dispejs.getText();
        skaitlis2 = Double.valueOf(teksts);
        
        
        
        switch(darbiba){
            case "/":
                this.dispejs.setText(String.valueOf(skaitlis1/skaitlis2));
                break;
            case "*":
                this.dispejs.setText(String.valueOf(skaitlis1*skaitlis2));
                break;
            case "-":
                this.dispejs.setText(String.valueOf(skaitlis1-skaitlis2));
                break;
            case "+":
                this.dispejs.setText(String.valueOf(skaitlis1+skaitlis2)); 
                break;
                
        }
        
    }//GEN-LAST:event_vienadsActionPerformed

    private void notiritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notiritActionPerformed
        this.dispejs.setText("");
    }//GEN-LAST:event_notiritActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorsArPogam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorsArPogam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorsArPogam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorsArPogam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorsArPogam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atnemt;
    private javax.swing.JButton cipars0;
    private javax.swing.JButton cipars1;
    private javax.swing.JButton cipars2;
    private javax.swing.JButton cipars3;
    private javax.swing.JButton cipars4;
    private javax.swing.JButton cipars5;
    private javax.swing.JButton cipars6;
    private javax.swing.JButton cipars7;
    private javax.swing.JButton cipars8;
    private javax.swing.JButton cipars9;
    private javax.swing.JButton dalit;
    private javax.swing.JTextField dispejs;
    private javax.swing.JButton notirit;
    private javax.swing.JButton reizinat;
    private javax.swing.JButton saskaitit;
    private javax.swing.JButton vienads;
    // End of variables declaration//GEN-END:variables
}
